client_id = "dd79d89d4e7877c4faa808d2345b228b"
name = "Kitty rama shipping"
application_url = "https://dense-plants-invite-intensive.trycloudflare.com"
embedded = true

api_version = "2024-01"

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = [
  "https://dense-plants-invite-intensive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_files,write_files,read_customers,read_purchase_options,write_purchase_options,read_own_subscription_contracts,write_own_subscription_contracts,read_content,write_content"