api_version = "2025-10"


[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "admin-update"
type = "ui_extension"
uid = "67dd0123-203a-3ab9-af7e-d3bd5e5b26f8310c59bb"

# Both targets need to be specified for the extensions to work
[[extensions.targeting]]
module = "./src/ProductExtension.jsx"
target = "admin.product-purchase-option.action.render"

[[extensions.targeting]]
module = "./src/ProductVariantExtension.jsx"
target = "admin.product-variant-purchase-option.action.render"

# Valid extension targets:

# Product index and detail pages
# - admin.product-purchase-option.action.render

# Product variant detail pages
# - admin.product-variant-purchase-option.action.render
