[[extensions]]

uid = "277ae083-dfcd-a386-798b-084e9161d6ad95ef2b0b"

type = "theme"
name = "subscription-widget"
handle = "subscription-widget"

  [[extensions.targeting]]
  target = "section"
  template = "product"
  block_type = "local"
  handle = "subscription"